default_platform(:android)

platform :android do
  desc "Upload APK to Firebase App Distribution"
  lane :firebase_distribution do
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      service_credentials_file: "firebase-service-account.json",
      groups: "qa-testers",
      release_notes: "Release #{ENV['RELEASE_VERSION']} uploaded from GitHub Actions. Commit: #{ENV['GITHUB_SHA']}",
      apk_path: "app/build/outputs/apk/debug/app-debug.apk"
    )
  end
end
