name: Android Build POC

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant Execute Permission
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Verify APK Exists
        run: |
          echo "Checking APK location..."
          ls -lah app/build/outputs/apk/debug/

          if [ -f app/build/outputs/apk/debug/app-debug.apk ]; then
            echo "APK FOUND SUCCESSFULLY"
          else
            echo "APK NOT FOUND"
            exit 1
          fi

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
